name: Guesthouse CI

on:
  push:
    branches:
      - main
      - develop
      - Pako-S

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:

  # ==========================================
  # ADMIN WEB
  # ==========================================
  admin-web:
    name: Admin Web CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: admin-web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: admin-web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build admin web
        run: npm run build


  # ==========================================
  # BACKEND
  # ==========================================
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build backend
        run: npm run build


  # ==========================================
  # MOBILE APP
  # ==========================================
  mobile-app:
    name: Mobile App CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: mobile-app/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Expo lint
        run: npm run lint
